### PR TITLE
Fix: properly install sources in share dir

### PR DESCRIPTION
**Pull request by mehw**
Hi,

I was trying to install HeeksCAD in Gentoo, but I had some trouble with **cmake**...
- `Picking.{h,cpp}` (see PR #423) and `CxfFont.h` were missing from the installation lists;
- `src/*` source files were not installed into `share/heekscad/src`;
- some file in `share/heekscad/` searches `tinyxml.h` in that location, rather than in `include/heekscad/`;
- as a bonus, `Plugins.cpp` should use the defined variable `LIB_INSTALL_DIR`.

### CODE REVIEW

**Comment by mehw** [comment]
With commit https://github.com/Heeks/heekscad/pull/425/commits/7c7cf14c8e0f9cbc7a402f4a35e97fb0837cfe53, there may be the need to be sure that `LIB_INSTALL_DIR` is just a directory name, and not a full path: `Plugins.cpp` uses `LIB_INSTALL_DIR` to build a path.

**Comment by mehw** [comment]
Commit https://github.com/Heeks/heekscad/pull/425/commits/65afea048b62767ee3759f905abdc943dc3072f4 is due to address [possible problems when building on Windows](https://github.com/Heeks/heekscnc/pull/201#issuecomment-553525020).

Cmake will autoconfigure `Plugins.cpp.in` to use the value of the defined variable `LIB_INSTALL_DIR`. It writes a configured `Plugins.cpp` file. When this doesn't happen, a pre-configured `Plugins.cpp` may help (in the commit "lib" is used as LIB_INSTALL_DIR value replacement).

**Comment by neomilium** [comment]
@mehw Thanks for your contribution. IHMO, your work is a good way to improve building system but @danheeks (the main author of this software) do not use CMake and do not care about packaging or programming good practices.

@danheeks lets contributions to be merged if he is able to work easily on top of it, on his setup. (or he will revert commit later if it dont work straightforward, e.g. your contribution on HeeksCNC).

My recommendation is to provide patches that will work out of the box on his setup or integrate your patches directly in your package recipe (i.e. `ebuild` on gentoo).

@danheeks : no offense in my words, you are happy and efficient your own way, I learn it few years ago ;-) nevertheless, as already said years ago, the day you want to work on a Unix-based system and want to use the power of CMake, I'll be happy to help.

**Comment by mehw** [comment]
Hi @neomilium,

Thanks for the explanation leading to the closure of the PR.

> @mehw Thanks for your contribution. IHMO, your work is a good way to improve building system but @danheeks (the main author of this software) do not use CMake and do not care about packaging or programming good practices.

So, basically the CMake build environment will not be so much maintained...? By the way, I had troubles compiling heekscad after commit 01ceb7c55c49e751d11c7b5e45eba45143d25e23. It seems that moving `Picking.{h,cpp}` from _src/_ to _interface/_ doesn't make heekscad's linking happy. I get a **undefined reference to SetPickingColor** error. Below you find the patch I use to fix the issue.

```
diff -Nuar a/src/CMakeLists.txt b/src/CMakeLists.txt
--- a/src/CMakeLists.txt	2020-06-15 12:32:01.309782824 +0000
+++ b/src/CMakeLists.txt	2020-06-15 12:31:46.169760618 +0000
@@ -236,7 +236,7 @@
 set( HeeksCAD_LIBS
        -L../bin -lheekstinyxml -lheeksintf
     )
-add_executable( heekscad ${heekscad_SRCS} ${platform_SRCS} )
+add_executable( heekscad ${heekscad_SRCS} ${platform_SRCS} ../interface/Picking.cpp )
 target_link_libraries( heekscad
                        ${wxWidgets_LIBRARIES} ${OpenCASCADE_LIBRARIES}
                        ${OPENGL_LIBRARIES} ${PYTHON_LIBRARIES} ${OSX_LIBS}
```

**Comment by neomilium** [comment]
Hi @mehw,

> So, basically the CMake build environment will not be so much maintained...?

Actually, it is more maintained than any other building system : almost all contributors are Unix-based OS users, so they use the _decent_ building system CMake is..
So, contributions on CMake are really welcome but should not disturb @danheeks 

> By the way, I had troubles compiling heekscad after commit [01ceb7c](https://github.com/Heeks/heekscad/commit/01ceb7c55c49e751d11c7b5e45eba45143d25e23). It seems that moving `Picking.{h,cpp}` from _src/_ to _interface/_ doesn't make heekscad's linking happy. I get a **undefined reference to SetPickingColor** error. Below you find the patch I use to fix the issue.

So bad, the code structure of this software is messy. Face to the problem that some code is shared by heekscad and some plugins, I moved the corresponding code in a dedicated library provided by `interface/` directory.

It may be solved by linking executable to the library provided by `interface/`, could you give it a try?

That's strange I'm not able to reproduce it locally on Debian / Ubuntu.

**Comment by mehw** [comment]
> It may be solved by linking executable to the library provided by `interface/`, could you give it a try?

In `src/CMakeLists.txt` the line `add_executable( heekscad ${heekscad_SRCS} ${platform_SRCS} ../interface/Picking.cpp )` is a way to achieve that just for the `interface/Picking.cpp.o` object file (see https://github.com/Heeks/heekscad/pull/425#issuecomment-644148511).

On Gentoo I can't compile heekscad without the above adjustment to the `src/CMakeLists.txt` file.

**Comment by neomilium** [comment]
I agree that's seems a bit dirty to me to add one source file this way while linking to library could make sense.

@mehw Could you give it a try?

**Comment by mehw** [comment]
Hi @neomilium,

About the **[undefined reference to SetPickingColor](https://github.com/Heeks/heekscad/pull/425#issuecomment-644148511)** error, generated when `heekscad` can't find `interface/Picking.cpp`...

> That's strange I'm not able to reproduce it locally on Debian / Ubuntu.
> 
> I agree that's seems a bit dirty to me to add one source file this way while linking to library could make sense.
> 
> @mehw Could you give it a try?

After removing heekscad completely from my system, recompiling gave this time an error about not finding the libraries `libheeksintf` and `libheekstinyxml`.

Apparently, after setting the directory searched for the libraries to a full path (see [CMAKE_CURRENT_BINARY_DIR](https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_BINARY_DIR.html)), there's no longer the need to add `../interface/Picking.cpp` to `add_executable`...

Probably, the libraries installed in my system took precedence over the new compiled ones, which with a relative path could not also be found.

```
diff -Nuar a/src/CMakeLists.txt b/src/CMakeLists.txt
--- a/src/CMakeLists.txt	2020-06-17 23:21:52.438241419 +0000
+++ b/src/CMakeLists.txt	2020-06-17 23:22:53.778331386 +0000
@@ -232,7 +232,7 @@
     )
 
 set( HeeksCAD_LIBS
-       -L../bin -lheekstinyxml -lheeksintf
+       -L"${CMAKE_CURRENT_BINARY_DIR}/../bin" -lheekstinyxml -lheeksintf
     )
 add_executable( heekscad ${heekscad_SRCS} ${platform_SRCS} )
 target_link_libraries( heekscad

```

**Comment by neomilium** [comment]
@mehw Your patch have been applied on master.

See 55af767c6b5da58fe0b30d7f70e8406ee4aaecbc

Thanks for your work.

**Comment by mehw** [comment]
Thanks @neomilium,

That makes me feel useful.

Cheers!

**Pull request closed without merging**
